#!/usr/bin/env python3
"""Compare reference forms for bounded symbolic music generation."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import platform
import random
import resource
import struct
import time
import wave
from collections import Counter, defaultdict
from copy import deepcopy
from fractions import Fraction
from pathlib import Path
from typing import Any, Callable


BASE_PATH = Path(__file__).with_name("phase6f-symbolic-representation.py")
BASE_SPEC = importlib.util.spec_from_file_location("phase6f_base", BASE_PATH)
if BASE_SPEC is None or BASE_SPEC.loader is None:
    raise RuntimeError(f"Cannot load {BASE_PATH}")
base = importlib.util.module_from_spec(BASE_SPEC)
BASE_SPEC.loader.exec_module(base)

SCHEMA = "ghostnote-reference-transfer-eval-v0"
PATCH_SCHEMA = "ghostnote-note-patch-v0"
ARMS = ("seed-only", "raw-reference", "extracted-structure", "mixed")
PROVIDERS = ("openai", "gemini")
TASKS = ("continuation", "motif_variation", "groove_transfer", "voice_leading", "arrangement_roles", "combined_transfer")
PERMISSION = "MIT generated project fixture"


def canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def digest(value: Any) -> str:
    return hashlib.sha256(canonical(value).encode()).hexdigest()


def frac(value: str | int | Fraction) -> Fraction:
    return value if isinstance(value, Fraction) else Fraction(str(value))


def ftext(value: str | int | Fraction) -> str:
    result = frac(value)
    return str(result.numerator) if result.denominator == 1 else f"{result.numerator}/{result.denominator}"


def note(note_id: str, track: str, start: str | int, duration: str | int, pitch: int, velocity: int, channel: int) -> dict[str, Any]:
    return base.note(note_id, track, start, duration, pitch, velocity, channel=channel)


def clip(clip_id: str, length: int, tracks: list[dict[str, Any]], notes: list[dict[str, Any]], harmony: list[dict[str, Any]]) -> dict[str, Any]:
    result = {
        "id": clip_id,
        "meter": "4/4",
        "length_beats": length,
        "tracks": tracks,
        "harmony": harmony,
        "permission": PERMISSION,
        "ownership_basis": "Generated by the phase 6g probe. It contains no third-party notes.",
        "coverage": {"start_beats": "0", "end_beats": str(length), "tracks_complete": True, "notes_complete": True},
        "notes": sorted(notes, key=lambda row: (frac(row["start"]), row["track"], row["pitch"], row["id"])),
    }
    result["sha256"] = digest(result)
    return result


def repeated_notes(prefix: str, track: str, channel: int, starts: list[Fraction], pitches: list[int], velocities: list[int], duration: Fraction = Fraction(1, 2)) -> list[dict[str, Any]]:
    return [
        note(f"{prefix}-{index + 1}", track, start, duration, pitch, velocities[index % len(velocities)], channel)
        for index, (start, pitch) in enumerate(zip(starts, pitches))
    ]


def make_cohort() -> dict[str, Any]:
    motif_seed = clip(
        "seed-motif-v0", 8,
        [{"id": "motif-lead", "role": "lead", "voice": "monophonic"}, {"id": "motif-bass", "role": "bass", "voice": "monophonic"}],
        repeated_notes("ms-l", "motif-lead", 0, [Fraction(0), Fraction(1), Fraction(3, 2), Fraction(3)], [60, 62, 65, 63], [92, 74, 86, 70])
        + repeated_notes("ms-b", "motif-bass", 1, [Fraction(0), Fraction(2), Fraction(4), Fraction(6)], [36, 41, 38, 43], [82], Fraction(3, 2)),
        [{"start": "0", "symbol": "Cm9"}, {"start": "4", "symbol": "Abmaj7"}],
    )
    motif_reference = clip(
        "reference-motif-v0", 16,
        [{"id": "reference-lead", "role": "lead", "voice": "monophonic"}, {"id": "reference-bass", "role": "bass", "voice": "monophonic"}],
        repeated_notes(
            "mr-l", "reference-lead", 0,
            [Fraction(bar + offset) for bar in (0, 4, 8, 12) for offset in (0, Fraction(3, 4), Fraction(3, 2), 3)],
            [pitch for root in (65, 67, 68, 70) for pitch in (root, root + 2, root + 5, root + 3)],
            [101, 73, 89, 67], Fraction(1, 2),
        ) + repeated_notes("mr-b", "reference-bass", 1, [Fraction(value) for value in range(0, 16, 2)], [41, 41, 46, 43, 44, 44, 48, 43], [84], Fraction(3, 2)),
        [{"start": str(start), "symbol": symbol} for start, symbol in zip(range(0, 16, 2), ("Fm9", "Fm9", "Bbm9", "Eb13", "Abmaj9", "Abmaj9", "Dbmaj9", "C7alt"))],
    )

    groove_seed = clip(
        "seed-groove-v0", 8,
        [{"id": "groove-keys", "role": "harmony", "voice": "polyphonic"}, {"id": "groove-bass", "role": "bass", "voice": "monophonic"}],
        repeated_notes("gs-k", "groove-keys", 0, [Fraction(0), Fraction(2), Fraction(4), Fraction(6)], [60, 65, 62, 67], [76], Fraction(3, 2))
        + repeated_notes("gs-b", "groove-bass", 1, [Fraction(0), Fraction(2), Fraction(4), Fraction(6)], [36, 41, 38, 43], [84], Fraction(3, 2)),
        [{"start": str(start), "symbol": symbol} for start, symbol in zip((0, 2, 4, 6), ("Cm9", "Fm9", "Dm7b5", "G7alt"))],
    )
    groove_starts = [Fraction(0), Fraction(17, 32), Fraction(1), Fraction(97, 64), Fraction(2), Fraction(81, 32), Fraction(3), Fraction(225, 64)]
    groove_reference = clip(
        "reference-groove-v0", 8,
        [{"id": "reference-drums", "role": "drums", "voice": "polyphonic"}, {"id": "reference-top", "role": "lead", "voice": "monophonic"}],
        repeated_notes("gr-d", "reference-drums", 9, groove_starts + [value + 4 for value in groove_starts], [36, 42, 38, 42, 36, 42, 38, 42] * 2, [112, 70, 103, 67, 108, 72, 101, 65], Fraction(1, 8))
        + repeated_notes("gr-t", "reference-top", 0, [Fraction(0), Fraction(2), Fraction(4), Fraction(6)], [69, 71, 70, 72], [88], Fraction(3, 2)),
        [{"start": str(start), "symbol": symbol} for start, symbol in zip((0, 2, 4, 6), ("Am9", "D13", "Gmaj9", "E7alt"))],
    )

    arrangement_seed = clip(
        "seed-arrangement-v0", 8,
        [
            {"id": "arr-lead", "role": "lead", "voice": "monophonic"},
            {"id": "arr-chords", "role": "harmony", "voice": "polyphonic"},
            {"id": "arr-bass", "role": "bass", "voice": "monophonic"},
            {"id": "arr-drums", "role": "drums", "voice": "polyphonic"},
        ],
        repeated_notes("as-l", "arr-lead", 0, [Fraction(0), Fraction(2), Fraction(4), Fraction(6)], [72, 74, 75, 77], [88], 1)
        + repeated_notes("as-b", "arr-bass", 2, [Fraction(0), Fraction(2), Fraction(4), Fraction(6)], [36, 36, 41, 43], [82], Fraction(3, 2))
        + repeated_notes("as-c", "arr-chords", 1, [Fraction(0), Fraction(4)], [60, 65], [72], 3)
        + repeated_notes("as-d", "arr-drums", 9, [Fraction(value) for value in range(8)], [36, 42, 38, 42, 36, 42, 38, 42], [96, 70], Fraction(1, 8)),
        [{"start": "0", "symbol": "Cm9"}, {"start": "4", "symbol": "Fm9"}],
    )
    role_reference = clip(
        "reference-roles-v0", 16,
        [
            {"id": "rr-lead", "role": "lead", "voice": "monophonic"},
            {"id": "rr-chords", "role": "harmony", "voice": "polyphonic"},
            {"id": "rr-bass", "role": "bass", "voice": "monophonic"},
            {"id": "rr-drums", "role": "drums", "voice": "polyphonic"},
        ],
        repeated_notes("rr-d", "rr-drums", 9, [Fraction(value) for value in range(16)], [36, 42, 38, 42] * 4, [98, 68], Fraction(1, 8))
        + repeated_notes("rr-b", "rr-bass", 2, [Fraction(value) for value in (0, 4, 8, 10, 12, 14)], [36, 41, 43, 41, 36, 43], [82], Fraction(3, 2))
        + repeated_notes("rr-c", "rr-chords", 1, [Fraction(value) for value in (4, 8, 12)], [60, 65, 67], [72], 3)
        + repeated_notes("rr-l", "rr-lead", 0, [Fraction(value) for value in (8, 9, 10, 11, 12, 14)], [72, 74, 75, 79, 77, 74], [90], Fraction(3, 4)),
        [{"start": str(start), "symbol": symbol} for start, symbol in zip((0, 4, 8, 12), ("Cm9", "Fm9", "G7sus", "Cm9"))],
    )
    texture_reference = clip(
        "reference-texture-v0", 16,
        [
            {"id": "tr-lead", "role": "lead", "voice": "monophonic"},
            {"id": "tr-chords", "role": "harmony", "voice": "polyphonic"},
            {"id": "tr-bass", "role": "bass", "voice": "monophonic"},
            {"id": "tr-drums", "role": "drums", "voice": "polyphonic"},
        ],
        repeated_notes("tr-d", "tr-drums", 9, [Fraction(value, 2) for value in range(32)], [36, 42, 38, 42] * 8, [104, 64, 91, 66], Fraction(1, 8))
        + repeated_notes("tr-b", "tr-bass", 2, [Fraction(value) for value in range(0, 16, 2)], [40, 43, 45, 47, 40, 43, 38, 35], [86], Fraction(3, 2))
        + sum(([
            note(f"tr-c-{bar}-{index}", "tr-chords", bar, 3, pitch, 70 - index * 2, 1)
            for index, pitch in enumerate(chord)
        ] for bar, chord in zip((0, 4, 8, 12), ((52, 59, 66), (55, 62, 69), (57, 64, 71), (50, 57, 64)))), []),
        [{"start": str(start), "symbol": symbol} for start, symbol in zip((0, 4, 8, 12), ("Em9", "Gmaj9", "Am9", "D13"))],
    )
    references = {item["id"]: item for item in (motif_reference, groove_reference, role_reference, texture_reference)}
    seeds = {item["id"]: item for item in (motif_seed, groove_seed, arrangement_seed)}
    pairs = {
        "motif": {"seed_id": motif_seed["id"], "reference_ids": [motif_reference["id"]], "tasks": ["continuation", "motif_variation"]},
        "groove": {"seed_id": groove_seed["id"], "reference_ids": [groove_reference["id"]], "tasks": ["groove_transfer", "voice_leading"]},
        "arrangement": {"seed_id": arrangement_seed["id"], "reference_ids": [role_reference["id"], texture_reference["id"]], "tasks": ["arrangement_roles", "combined_transfer"]},
    }
    result = {"seeds": seeds, "references": references, "pairs": pairs}
    result["sha256"] = digest(result)
    return result


def render_bar(item: dict[str, Any], coverage_end: Fraction | None = None) -> str:
    end = frac(item["length_beats"]) if coverage_end is None else coverage_end
    lines = [
        f"score {item['id']} hash={item['sha256']} meter={item['meter']} length={item['length_beats']}b",
        f"permission={item['permission']} coverage=[0,{ftext(end)}) complete={str(coverage_end is None).lower()}",
    ]
    lines.extend(f"track {row['id']} role={row['role']} voice={row['voice']}" for row in item["tracks"])
    lines.extend(f"harmony at={row['start']} symbol={row['symbol']}" for row in item["harmony"] if frac(row["start"]) < end)
    for row in item["notes"]:
        if frac(row["start"]) >= end:
            continue
        bar_number = int(frac(row["start"]) // 4) + 1
        offset = frac(row["start"]) % 4
        lines.append(f"{row['id']} {row['track']} b{bar_number}+{ftext(offset)} dur={row['duration']} p{row['pitch']} v{row['velocity']}")
    return "\n".join(lines)


def structure(item: dict[str, Any]) -> dict[str, Any]:
    role_by_track = {row["id"]: row["role"] for row in item["tracks"]}
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in item["notes"]:
        grouped[role_by_track[row["track"]]].append(row)
    roles = {}
    for role, notes in sorted(grouped.items()):
        by_bar = Counter(int(frac(row["start"]) // 4) + 1 for row in notes)
        onsets = sorted({ftext(frac(row["start"]) % 4) for row in notes}, key=frac)
        velocities = [row["velocity"] for row in notes]
        pitches = [row["pitch"] for row in sorted(notes, key=lambda value: frac(value["start"]))]
        roles[role] = {
            "active_bars": sorted(by_bar),
            "notes_per_bar": {str(key): value for key, value in sorted(by_bar.items())},
            "onsets_mod_bar": onsets,
            "accent_threshold": 90,
            "accent_onsets_mod_bar": sorted({ftext(frac(row["start"]) % 4) for row in notes if row["velocity"] >= 90}, key=frac),
            "median_velocity": sorted(velocities)[len(velocities) // 2],
            "pitch_interval_signs": [int(second > first) - int(second < first) for first, second in zip(pitches, pitches[1:])],
            "pitch_span": max(pitches) - min(pitches),
        }
    harmony_starts = [row["start"] for row in item["harmony"]]
    return {"source_id": item["id"], "source_sha256": item["sha256"], "coverage": item["coverage"], "permission": item["permission"], "harmony_change_beats": harmony_starts, "roles": roles}


TASK_LIMITS = {
    "continuation": {"seed": "seed-motif-v0", "start": "8", "end": "24", "tracks": ["motif-lead", "motif-bass"], "pitch_range": [36, 84], "note_count": [16, 28], "required": "Continue for four bars. End at beat 24. Keep both roles."},
    "motif_variation": {"seed": "seed-motif-v0", "start": "8", "end": "12", "tracks": ["motif-lead"], "pitch_range": [55, 84], "note_count": [4, 8], "required": "Keep the seed lead motif interval identity +2,+3,-2. Change its rhythm or register."},
    "groove_transfer": {"seed": "seed-groove-v0", "start": "8", "end": "16", "tracks": ["groove-keys"], "pitch_range": [48, 84], "note_count": [8, 20], "required": "Use only target harmony pitch classes C,D,Eb,F,G,Ab,Bb. Transfer groove and accent structure."},
    "voice_leading": {"seed": "seed-groove-v0", "start": "8", "end": "16", "tracks": ["groove-keys"], "pitch_range": [60, 84], "note_count": [4, 10], "required": "Make a new melody over Dm9,G13,Cmaj9,A7alt at beats 8,10,12,14. Transfer harmonic rhythm and contour behavior."},
    "arrangement_roles": {"seed": "seed-arrangement-v0", "start": "8", "end": "24", "tracks": ["arr-lead", "arr-chords", "arr-bass", "arr-drums"], "pitch_range": [35, 84], "note_count": [20, 56], "required": "Continue for four bars. Apply the reference role-entry and role-exit plan."},
    "combined_transfer": {"seed": "seed-arrangement-v0", "start": "8", "end": "24", "tracks": ["arr-lead", "arr-chords", "arr-bass", "arr-drums"], "pitch_range": [35, 84], "note_count": [28, 64], "required": "Use role structure from reference-roles-v0. Use rhythm, density, and voicing from reference-texture-v0."},
}


def coverage_for_arm(arm: str, cohort: dict[str, Any]) -> dict[str, Any]:
    rows = {}
    for reference_id, item in cohort["references"].items():
        if arm in {"seed-only", "notochord"}:
            rows[reference_id] = {"form": "none", "coverage": None, "sha256": item["sha256"], "permission": item["permission"]}
        elif arm == "raw-reference":
            rows[reference_id] = {"form": "raw compact bars", "coverage": item["coverage"], "sha256": item["sha256"], "permission": item["permission"]}
        elif arm == "extracted-structure":
            rows[reference_id] = {"form": "extracted structure", "coverage": item["coverage"], "sha256": item["sha256"], "permission": item["permission"]}
        else:
            rows[reference_id] = {"form": "extracted structure plus first-bar excerpt", "coverage": {"structure": item["coverage"], "excerpt": {"start_beats": "0", "end_beats": "4"}}, "sha256": item["sha256"], "permission": item["permission"]}
    return rows


def render_context(arm: str, cohort: dict[str, Any]) -> str:
    blocks = ["SEEDS"]
    blocks.extend(render_bar(item) for item in cohort["seeds"].values())
    blocks.append("REFERENCES")
    if arm == "seed-only":
        blocks.append("No reference content is available. Do not claim a reference trait.")
    elif arm == "raw-reference":
        blocks.extend(render_bar(item) for item in cohort["references"].values())
    elif arm == "extracted-structure":
        blocks.extend(canonical(structure(item)) for item in cohort["references"].values())
    else:
        for item in cohort["references"].values():
            blocks.append(canonical(structure(item)))
            blocks.append("SELECTED EXCERPT\n" + render_bar(item, Fraction(4)))
    return "\n\n".join(blocks)


def task_prompt(arm: str, cohort: dict[str, Any]) -> str:
    limits = canonical(TASK_LIMITS)
    coverage = canonical(coverage_for_arm(arm, cohort))
    return f"""You are in a controlled symbolic music study. Return one JSON object only.
The notes are generated project fixtures under the repository MIT license. One beat is one quarter note. Use exact rational strings for all times. Do not copy pitches only to appear similar. Keep useful trait transfer separate from exact copying.

Return schema={SCHEMA}, arm={arm}, reference_coverage copied exactly from REFERENCE COVERAGE, and results. Results must contain exactly these task keys: {','.join(TASKS)}.
Each task value must contain status, patch, and explanation. Use status=complete when you can satisfy the task. Use status=unavailable only when the missing reference makes the requested transfer impossible. Even when a reference is missing, make a valid musical proposal from the seed and state that reference transfer is unavailable in the explanation.
Each patch uses schema={PATCH_SCHEMA}, the exact seed base_sha256, and one insert op. The insert op has default_policy=track-neutral-v0 and notes. Each note has id, track, start, duration, pitch, and velocity only. Do not return channel, mute, release velocity, or expression. Keep notes inside the task start and end. An end is exclusive for note starts and inclusive for note ends. Use unique IDs with the task key as a prefix. Avoid same-pitch overlaps and monophonic overlaps.

TASK LIMITS
{limits}

REFERENCE COVERAGE
{coverage}

{render_context(arm, cohort)}
"""


def supported_time(value: Any) -> bool:
    try:
        number = frac(value)
    except (TypeError, ValueError, ZeroDivisionError):
        return False
    return number.denominator <= 768 and (512 % number.denominator == 0 or 768 % number.denominator == 0)


def compile_task_patch(task: str, patch: Any, cohort: dict[str, Any]) -> tuple[list[dict[str, Any]] | None, list[str]]:
    limits = TASK_LIMITS[task]
    seed = cohort["seeds"][limits["seed"]]
    errors = base.patch_errors(patch, seed)
    if errors:
        return None, errors
    operations = patch.get("ops", [])
    if len(operations) != 1 or operations[0].get("op") != "insert":
        return None, ["one insert operation is required"]
    inserted = operations[0]["notes"]
    minimum, maximum = limits["note_count"]
    if not minimum <= len(inserted) <= maximum:
        errors.append(f"note count must be {minimum} through {maximum}")
    allowed_tracks = set(limits["tracks"])
    low, high = limits["pitch_range"]
    for row in inserted:
        if row.get("track") not in allowed_tracks:
            errors.append(f"note {row.get('id')} has a forbidden track")
        if isinstance(row.get("pitch"), int) and not low <= row["pitch"] <= high:
            errors.append(f"note {row.get('id')} is outside the task pitch range")
        if not supported_time(row.get("start")) or not supported_time(row.get("duration")):
            errors.append(f"note {row.get('id')} uses unsupported timing")
            continue
        start, end = frac(row["start"]), frac(row["start"]) + frac(row["duration"])
        if start < frac(limits["start"]) or start >= frac(limits["end"]) or end > frac(limits["end"]):
            errors.append(f"note {row.get('id')} is outside the target window")
    if errors:
        return None, errors
    try:
        candidate = base.compile_patch(patch, seed)
    except ValueError as error:
        return None, [str(error)]
    inserted_ids = {row["id"] for row in inserted}
    output = [row for row in candidate if row["id"] in inserted_ids]
    tracks = {row["id"]: row for row in seed["tracks"]}
    for track_id, rows in _group(output, lambda row: row["track"]).items():
        if tracks[track_id]["voice"] != "monophonic":
            continue
        ordered = sorted(rows, key=lambda row: frac(row["start"]))
        for first, second in zip(ordered, ordered[1:]):
            if frac(first["start"]) + frac(first["duration"]) > frac(second["start"]):
                errors.append(f"monophonic notes {first['id']} and {second['id']} overlap")
    if errors:
        return None, errors
    return output, []


def _group(values: list[dict[str, Any]], key: Callable[[dict[str, Any]], Any]) -> dict[Any, list[dict[str, Any]]]:
    result: dict[Any, list[dict[str, Any]]] = defaultdict(list)
    for value in values:
        result[key(value)].append(value)
    return result


def signs(values: list[int]) -> list[int]:
    return [int(second > first) - int(second < first) for first, second in zip(values, values[1:])]


def longest_common(left: list[Any], right: list[Any]) -> int:
    if not left or not right:
        return 0
    previous = [0] * (len(right) + 1)
    best = 0
    for left_value in left:
        current = [0]
        for index, right_value in enumerate(right, 1):
            value = previous[index - 1] + 1 if left_value == right_value else 0
            current.append(value)
            best = max(best, value)
        previous = current
    return best


def jaccard(left: set[Any], right: set[Any]) -> float:
    union = left | right
    return 1.0 if not union else len(left & right) / len(union)


def cosine(left: Counter[Any], right: Counter[Any]) -> float:
    keys = set(left) | set(right)
    numerator = sum(left[key] * right[key] for key in keys)
    denominator = math.sqrt(sum(value * value for value in left.values()) * sum(value * value for value in right.values()))
    return 0.0 if denominator == 0 else numerator / denominator


def normalized_rows(item: dict[str, Any], role_by_track: dict[str, str], origin: Fraction = Fraction()) -> list[tuple[Any, ...]]:
    rows = []
    for row in sorted(item["notes"], key=lambda value: (frac(value["start"]), value["track"], value["pitch"])):
        rows.append((role_by_track[row["track"]], ftext(frac(row["start"]) - origin), row["duration"], row["pitch"], row["velocity"]))
    return rows


def similarity(output: list[dict[str, Any]], reference: dict[str, Any], seed: dict[str, Any]) -> dict[str, float | int]:
    out_roles = {row["id"]: row["role"] for row in seed["tracks"]}
    ref_roles = {row["id"]: row["role"] for row in reference["tracks"]}
    origin = min((frac(row["start"]) for row in output), default=Fraction())
    output_view = {"notes": output}
    out_rows = normalized_rows(output_view, out_roles, origin)
    ref_rows = normalized_rows(reference, ref_roles)
    out_onsets = {row[1] for row in out_rows}
    ref_onsets = {row[1] for row in ref_rows}
    out_pitches = [row[3] for row in out_rows]
    ref_pitches = [row[3] for row in ref_rows]
    out_intervals = signs(out_pitches)
    ref_intervals = signs(ref_pitches)
    out_density = len(out_rows) / max(1, int((max((frac(row[1]) for row in out_rows), default=Fraction()) + 4) // 4))
    ref_density = len(ref_rows) / (reference["length_beats"] / 4)
    return {
        "pitch_class_cosine": round(cosine(Counter(value % 12 for value in out_pitches), Counter(value % 12 for value in ref_pitches)), 6),
        "rhythm_onset_jaccard": round(jaccard(out_onsets, ref_onsets), 6),
        "contour_longest_events": longest_common(out_intervals, ref_intervals),
        "harmony_pitch_class_jaccard": round(jaccard({value % 12 for value in out_pitches}, {value % 12 for value in ref_pitches}), 6),
        "density_similarity": round(min(out_density, ref_density) / max(out_density, ref_density), 6),
        "role_jaccard": round(jaccard({row[0] for row in out_rows}, {row[0] for row in ref_rows}), 6),
    }


def direct_copy(output: list[dict[str, Any]], reference: dict[str, Any], seed: dict[str, Any]) -> dict[str, int]:
    out_roles = {row["id"]: row["role"] for row in seed["tracks"]}
    ref_roles = {row["id"]: row["role"] for row in reference["tracks"]}
    origin = min((frac(row["start"]) for row in output), default=Fraction())
    out_rows = normalized_rows({"notes": output}, out_roles, origin)
    ref_rows = normalized_rows(reference, ref_roles)
    exact = set(out_rows) & set(ref_rows)
    out_note_sequence = [(row[0], row[2], row[3], row[4]) for row in out_rows]
    ref_note_sequence = [(row[0], row[2], row[3], row[4]) for row in ref_rows]
    out_rhythm_sequence = [(row[0], row[1], row[2]) for row in out_rows]
    ref_rhythm_sequence = [(row[0], row[1], row[2]) for row in ref_rows]
    longest_events = longest_common(out_rows, ref_rows)
    return {
        "exact_event_count": len(exact),
        "longest_exact_note_sequence": longest_common(out_note_sequence, ref_note_sequence),
        "longest_exact_rhythm_sequence": longest_common(out_rhythm_sequence, ref_rhythm_sequence),
        "longest_unchanged_event_span": longest_events,
    }


def useful_trait_score(task: str, output: list[dict[str, Any]], cohort: dict[str, Any]) -> dict[str, Any]:
    limits = TASK_LIMITS[task]
    seed = cohort["seeds"][limits["seed"]]
    origin = frac(limits["start"])
    ordered = sorted(output, key=lambda row: (frac(row["start"]), row["track"], row["pitch"]))
    if task == "continuation":
        roles = {row["id"]: row["role"] for row in seed["tracks"]}
        active_roles = {roles[row["track"]] for row in output}
        reaches_end = max((frac(row["start"]) + frac(row["duration"]) for row in output), default=Fraction()) == frac(limits["end"])
        return {"passed": int(active_roles == {"lead", "bass"}) + int(reaches_end), "total": 2, "active_roles": sorted(active_roles), "reaches_end": reaches_end}
    if task == "motif_variation":
        pitches = [row["pitch"] for row in ordered]
        target = [1, 1, -1]
        motif = longest_common(signs(pitches), target) >= 3
        seed_rhythm = ["1", "1/2", "3/2"]
        rhythms = [ftext(frac(second["start"]) - frac(first["start"])) for first, second in zip(ordered, ordered[1:])]
        varied = rhythms[:3] != seed_rhythm
        return {"passed": int(motif) + int(varied), "total": 2, "motif_identity": motif, "rhythm_changed": varied}
    if task == "groove_transfer":
        target_pcs = {0, 2, 3, 5, 7, 8, 10}
        harmony = all(row["pitch"] % 12 in target_pcs for row in output)
        reference = cohort["references"]["reference-groove-v0"]
        reference_onsets = {frac(row["start"]) % 4 for row in reference["notes"] if row["track"] == "reference-drums"}
        output_onsets = {(frac(row["start"]) - origin) % 4 for row in output}
        rhythm = len(output_onsets & reference_onsets) >= 4
        accents = {frac(row["start"]) % 4 for row in reference["notes"] if row["velocity"] >= 100}
        output_accents = {(frac(row["start"]) - origin) % 4 for row in output if row["velocity"] >= 100}
        accent = len(accents & output_accents) >= 2
        return {"passed": sum((harmony, rhythm, accent)), "total": 3, "new_harmony": harmony, "rhythm": rhythm, "accent": accent}
    if task == "voice_leading":
        melody = []
        for beat in (8, 10, 12, 14):
            pitches = [row["pitch"] for row in output if frac(row["start"]) == beat]
            if pitches:
                melody.append(max(pitches))
        contour = signs(melody) == [1, -1, 1]
        harmonic_rhythm = len(melody) == 4
        return {"passed": int(contour) + int(harmonic_rhythm), "total": 2, "contour": contour, "harmonic_rhythm": harmonic_rhythm}
    role_by_track = {row["id"]: row["role"] for row in seed["tracks"]}
    active = defaultdict(set)
    for row in output:
        active[role_by_track[row["track"]]].add(int((frac(row["start"]) - origin) // 4) + 1)
    structure_match = active["drums"] == {1, 2, 3, 4} and active["bass"] == {1, 2, 3, 4} and active["harmony"] == {2, 3, 4} and active["lead"] == {3, 4}
    if task == "arrangement_roles":
        return {"passed": int(structure_match), "total": 1, "role_plan": structure_match, "active_bars": {key: sorted(value) for key, value in active.items()}}
    texture = cohort["references"]["reference-texture-v0"]
    ref_counts = Counter(int(frac(row["start"]) // 4) + 1 for row in texture["notes"])
    out_counts = Counter(int((frac(row["start"]) - origin) // 4) + 1 for row in output)
    density = all(abs(out_counts[bar] - ref_counts[bar]) <= 3 for bar in range(1, 5))
    ref_rhythm = {frac(row["start"]) % 1 for row in texture["notes"]}
    out_rhythm = {(frac(row["start"]) - origin) % 1 for row in output}
    rhythm = {Fraction(0), Fraction(1, 2)} <= out_rhythm and jaccard(out_rhythm, ref_rhythm) >= 0.5
    harmony_rows = [row for row in output if role_by_track[row["track"]] == "harmony"]
    grouped = _group(harmony_rows, lambda row: row["start"])
    voicing = any(len(rows) >= 3 and max(row["pitch"] for row in rows) - min(row["pitch"] for row in rows) >= 12 for rows in grouped.values())
    return {"passed": sum((structure_match, density, rhythm, voicing)), "total": 4, "role_plan": structure_match, "density": density, "rhythm": rhythm, "voicing": voicing}


def validate_result(result: dict[str, Any], arm: str, cohort: dict[str, Any]) -> dict[str, Any]:
    schema_valid = result.get("schema") == SCHEMA and result.get("arm") == arm
    coverage_valid = result.get("reference_coverage") == coverage_for_arm(arm, cohort)
    values = result.get("results") if isinstance(result.get("results"), dict) else {}
    rows = {}
    for task in TASKS:
        value = values.get(task) if isinstance(values.get(task), dict) else {}
        output, errors = compile_task_patch(task, value.get("patch"), cohort)
        if output is None:
            rows[task] = {"valid": False, "errors": errors, "status": value.get("status"), "trait": {"passed": 0, "total": 1}, "similarity": {}, "direct_copy": {}}
            continue
        pair = next(row for row in cohort["pairs"].values() if task in row["tasks"])
        references = [cohort["references"][reference_id] for reference_id in pair["reference_ids"]]
        seed = cohort["seeds"][pair["seed_id"]]
        rows[task] = {
            "valid": True,
            "errors": [],
            "status": value.get("status"),
            "trait": useful_trait_score(task, output, cohort),
            "similarity": {reference["id"]: similarity(output, reference, seed) for reference in references},
            "direct_copy": {reference["id"]: direct_copy(output, reference, seed) for reference in references},
            "compiled_sha256": digest(output),
            "compiled_notes": output,
        }
    return {
        "schema_valid": schema_valid,
        "coverage_valid": coverage_valid,
        "syntax_success": isinstance(result, dict),
        "tasks": rows,
        "valid_tasks": sum(row["valid"] for row in rows.values()),
        "trait_passed": sum(row["trait"]["passed"] for row in rows.values()),
        "trait_total": sum(row["trait"]["total"] for row in rows.values()),
    }


def repair_prompt(validation: dict[str, Any]) -> str:
    failures = {task: row["errors"] for task, row in validation["tasks"].items() if not row["valid"]}
    windows = {task: {"absolute_start": TASK_LIMITS[task]["start"], "absolute_end": TASK_LIMITS[task]["end"]} for task in failures}
    return (
        "Repair only the invalid task patches. Return the complete required result object again. "
        "The operation field is named op and its exact value is insert. Never use type instead of op. "
        "All note starts are absolute beat positions. "
        f"Validator errors: {canonical(failures)}. Absolute windows: {canonical(windows)}"
    )


def deterministic_results(cohort: dict[str, Any]) -> dict[str, Any]:
    def patch(task: str, rows: list[tuple[str, str, Any, Any, int, int]]) -> dict[str, Any]:
        seed = cohort["seeds"][TASK_LIMITS[task]["seed"]]
        return {"schema": PATCH_SCHEMA, "base_sha256": seed["sha256"], "ops": [{"op": "insert", "default_policy": "track-neutral-v0", "notes": [
            {"id": f"{task}-{index + 1}", "track": track, "start": ftext(start), "duration": ftext(duration), "pitch": pitch, "velocity": velocity}
            for index, (unused_id, track, start, duration, pitch, velocity) in enumerate(rows)
        ]}]}
    continuation = []
    for bar, root in zip((8, 12, 16, 20), (65, 67, 68, 70)):
        continuation.extend((
            ("", "motif-lead", bar, "1/2", root, 101), ("", "motif-lead", Fraction(bar) + Fraction(3, 4), "1/2", root + 2, 73),
            ("", "motif-lead", Fraction(bar) + Fraction(3, 2), "1/2", root + 5, 89), ("", "motif-lead", bar + 3, 1, root + 3, 67),
            ("", "motif-bass", bar, "3/2", 36 + (bar // 4) % 5, 84),
        ))
    groove = [("", "groove-keys", Fraction(8) + start, "1/8", (60, 62, 63, 65, 67, 68, 70, 72)[index], (112, 70, 103, 67, 108, 72, 101, 65)[index]) for index, start in enumerate([Fraction(0), Fraction(17, 32), Fraction(1), Fraction(97, 64), Fraction(2), Fraction(81, 32), Fraction(3), Fraction(225, 64)])]
    groove += [("", "groove-keys", Fraction(12) + start, "1/8", (60, 62, 63, 65, 67, 68, 70, 72)[index], (108, 68, 101, 65, 105, 70, 99, 63)[index]) for index, start in enumerate([Fraction(0), Fraction(17, 32), Fraction(1), Fraction(97, 64), Fraction(2), Fraction(81, 32), Fraction(3), Fraction(225, 64)])]
    role_rows = []
    for bar in range(4):
        start = 8 + bar * 4
        role_rows.extend((
            ("", "arr-drums", start, "1/8", 36, 98), ("", "arr-drums", start + 1, "1/8", 38, 92),
            ("", "arr-bass", start, "3/2", 36 + bar * 2, 82), ("", "arr-bass", start + 2, "3/2", 41 + bar, 80),
        ))
        if bar >= 1:
            role_rows.extend((
                ("", "arr-chords", start, 3, 48 + bar, 72), ("", "arr-chords", start, 3, 55 + bar, 70), ("", "arr-chords", start, 3, 62 + bar, 68),
            ))
        if bar >= 2:
            role_rows.extend((
                ("", "arr-lead", start, "3/4", 72 + bar, 90), ("", "arr-lead", start + 2, "3/4", 75 + bar, 86),
            ))
    combined = deepcopy(role_rows)
    for bar in range(4):
        start = 8 + bar * 4
        combined.extend((
            ("", "arr-drums", Fraction(start) + Fraction(1, 2), "1/8", 42, 66),
            ("", "arr-drums", Fraction(start) + Fraction(3, 2), "1/8", 42, 64),
            ("", "arr-drums", start + 2, "1/8", 39, 78),
            ("", "arr-drums", Fraction(start) + Fraction(5, 2), "1/8", 42, 66),
            ("", "arr-drums", start + 3, "1/8", 39, 76),
            ("", "arr-drums", Fraction(start) + Fraction(7, 2), "1/8", 42, 64),
        ))
    raw = {
        "continuation": patch("continuation", continuation),
        "motif_variation": patch("motif_variation", [("", "motif-lead", 8, "1/2", 67, 94), ("", "motif-lead", Fraction(35, 4), "1/2", 69, 74), ("", "motif-lead", Fraction(19, 2), "1/2", 72, 88), ("", "motif-lead", 11, 1, 70, 70)]),
        "groove_transfer": patch("groove_transfer", groove),
        "voice_leading": patch("voice_leading", [("", "groove-keys", 8, "3/2", 65, 88), ("", "groove-keys", 10, "3/2", 67, 86), ("", "groove-keys", 12, "3/2", 66, 84), ("", "groove-keys", 14, 2, 69, 90)]),
        "arrangement_roles": patch("arrangement_roles", role_rows),
        "combined_transfer": patch("combined_transfer", combined),
    }
    return {"schema": SCHEMA, "arm": "deterministic", "reference_coverage": coverage_for_arm("extracted-structure", cohort), "results": {task: {"status": "complete", "patch": value, "explanation": "A deterministic rule applies the requested measured traits."} for task, value in raw.items()}}


def notochord_gate() -> dict[str, Any]:
    return {
        "classification": "approved-for-bounded-experiment",
        "stage": "operator-approved",
        "downloaded": True,
        "package": {"name": "notochord", "version": "0.8.0", "license": "MIT", "wheel_bytes": 104200, "python": ">=3.10,<3.14"},
        "checkpoint": {"name": "notochord_lakh_50G_deep.pt", "release": "notochord-v0.4.0", "content_length_bytes": 213035415, "separate_terms_found": False, "training_dataset": "Lakh MIDI Dataset"},
        "events": ["ProgramChange", "NoteOn", "NoteOff"],
        "determinism_controls": ["application seed", "PyTorch seed", "bounded sub-event constraints"],
        "operator_basis": "The operator confirmed that the Lakh license is sufficient for this experiment and directed the run to continue.",
        "remaining_note": "The checkpoint release does not state separate terms. Record the code, checkpoint, and training provenance separately.",
        "sources": [
            "https://pypi.org/project/notochord/",
            "https://github.com/Intelligent-Instruments-Lab/notochord",
            "https://github.com/Intelligent-Instruments-Lab/iil-python-tools/releases/tag/notochord-v0.4.0",
            "https://arxiv.org/abs/2403.12000",
            "https://colinraffel.com/projects/lmd/",
        ],
    }


def directory_bytes(path: Path) -> int:
    return sum(item.stat().st_size for item in path.rglob("*") if item.is_file())


def seed_instruments(seed: dict[str, Any]) -> dict[str, int]:
    role_to_instrument = {"lead": 1, "harmony": 5, "bass": 34, "drums": 129}
    roles = {row["id"]: row["role"] for row in seed["tracks"]}
    return {track_id: role_to_instrument[role] for track_id, role in roles.items()}


def feed_seed(model: Any, seed: dict[str, Any]) -> None:
    instruments = seed_instruments(seed)
    events = []
    for row in seed["notes"]:
        events.append((frac(row["start"]), 1, instruments[row["track"]], row["pitch"], row["velocity"]))
        events.append((frac(row["start"]) + frac(row["duration"]), 0, instruments[row["track"]], row["pitch"], 0))
    cursor = Fraction()
    for position, unused_order, instrument, pitch, velocity in sorted(events):
        model.feed(instrument, pitch, float(position - cursor) * 0.5, velocity)
        cursor = position


def notochord_task(model: Any, task: str, cohort: dict[str, Any], run_seed: int) -> tuple[dict[str, Any], dict[str, Any]]:
    import torch

    limits = TASK_LIMITS[task]
    seed = cohort["seeds"][limits["seed"]]
    instruments_by_track = seed_instruments(seed)
    tracks_by_instrument = {instrument: track for track, instrument in instruments_by_track.items() if track in limits["tracks"]}
    allowed_instruments = set(tracks_by_instrument)
    low, high = limits["pitch_range"]
    allowed_pitches = set(range(low, high + 1))
    allowed_drums = set(range(max(35, low), min(51, high) + 1))
    torch.manual_seed(run_seed)
    random.seed(run_seed)
    model.reset()
    feed_seed(model, seed)
    current_seconds = 0.0
    target_seconds = float(frac(limits["end"]) - frac(limits["start"])) * 0.5
    active: dict[tuple[int, int], tuple[Fraction, int]] = {}
    completed = []
    raw_events = []
    quantization_errors = []
    max_notes = limits["note_count"][1]
    for event_index in range(320):
        started = time.perf_counter()
        event = model.query(
            include_inst=allowed_instruments,
            include_pitch=allowed_pitches,
            include_drum=allowed_drums,
            min_time=0.005,
            max_time=min(0.75, max(0.005, target_seconds - current_seconds)),
            min_vel=0,
            max_vel=120,
            allow_end=False,
        )
        query_ms = (time.perf_counter() - started) * 1000
        current_seconds += float(event["time"])
        if current_seconds > target_seconds + 1e-9:
            break
        model.feed(**event)
        exact_beat = frac(limits["start"]) + Fraction(current_seconds * 2).limit_denominator(10**9)
        quantized_beat = Fraction(round(float(exact_beat) * 512), 512)
        quantization_errors.append(abs(float(exact_beat - quantized_beat)))
        instrument, pitch = int(event["inst"]), int(event["pitch"])
        velocity = int(round(float(event["vel"])))
        raw_events.append({"instrument": instrument, "pitch": pitch, "time_seconds": float(event["time"]), "velocity": velocity, "query_ms": query_ms})
        key = (instrument, pitch)
        if velocity > 0 and len(active) + len(completed) < max_notes:
            active[key] = (quantized_beat, max(1, min(127, velocity)))
        elif velocity <= 0 and key in active:
            start, onset_velocity = active.pop(key)
            duration = max(Fraction(1, 512), quantized_beat - start)
            completed.append((instrument, start, duration, pitch, onset_velocity))
        if current_seconds >= target_seconds:
            break
    target_end = frac(limits["end"])
    for (instrument, pitch), (start, onset_velocity) in active.items():
        default_duration = Fraction(1, 8) if instrument >= 129 else Fraction(1, 2)
        duration = min(default_duration, target_end - start)
        if duration > 0:
            completed.append((instrument, start, duration, pitch, onset_velocity))
    completed = sorted(completed, key=lambda row: (row[1], row[0], row[3]))[:max_notes]
    notes = [
        {"id": f"{task}-noto-{index + 1}", "track": tracks_by_instrument[instrument], "start": ftext(start), "duration": ftext(duration), "pitch": pitch, "velocity": velocity}
        for index, (instrument, start, duration, pitch, velocity) in enumerate(completed)
    ]
    patch = {"schema": PATCH_SCHEMA, "base_sha256": seed["sha256"], "ops": [{"op": "insert", "default_policy": "track-neutral-v0", "notes": notes}]}
    diagnostics = {
        "raw_event_count": len(raw_events),
        "note_count": len(notes),
        "query_latency_ms": {
            "minimum": min((row["query_ms"] for row in raw_events), default=0),
            "median": sorted((row["query_ms"] for row in raw_events))[len(raw_events) // 2] if raw_events else 0,
            "maximum": max((row["query_ms"] for row in raw_events), default=0),
        },
        "maximum_quantization_error_beats": max(quantization_errors, default=0),
        "raw_sha256": digest([{key: value for key, value in row.items() if key != "query_ms"} for row in raw_events]),
    }
    return patch, diagnostics


def run_notochord(checkpoint: Path, install_root: Path) -> dict[str, Any]:
    import appdirs
    import importlib.metadata
    import psutil
    import torch

    data_dir = install_root / "data"
    appdirs.user_data_dir = lambda *args, **kwargs: str(data_dir)
    from notochord import Notochord

    process = psutil.Process()
    rss_before = process.memory_info().rss
    started = time.perf_counter()
    model = Notochord.from_checkpoint(checkpoint)
    startup_ms = (time.perf_counter() - started) * 1000
    rss_loaded = process.memory_info().rss
    cohort = make_cohort()
    task_rows = {}
    repeat_hashes = {}
    deterministic_matches = 0
    started = time.perf_counter()
    for index, task in enumerate(TASKS):
        patch, diagnostics = notochord_task(model, task, cohort, 6100 + index)
        repeated_patch, repeated_diagnostics = notochord_task(model, task, cohort, 6100 + index)
        repeat_hashes[task] = [digest(patch), digest(repeated_patch)]
        deterministic_matches += int(patch == repeated_patch and diagnostics["raw_sha256"] == repeated_diagnostics["raw_sha256"])
        task_rows[task] = {"status": "complete", "patch": patch, "explanation": "Notochord received the same MIDI seed prefix. It received no reference excerpt or extracted structure."}
        task_rows[task]["diagnostics"] = diagnostics
    inference_ms = (time.perf_counter() - started) * 1000
    result = {"schema": SCHEMA, "arm": "notochord", "reference_coverage": coverage_for_arm("notochord", cohort), "results": task_rows}
    validation = validate_result(result, "notochord", cohort)
    checkpoint_hash = hashlib.sha256(checkpoint.read_bytes()).hexdigest()
    return {
        "schema": SCHEMA,
        "provider": "notochord",
        "model": "notochord_lakh_50G_deep.pt",
        "package_version": importlib.metadata.version("notochord"),
        "torch_version": torch.__version__,
        "checkpoint_sha256": checkpoint_hash,
        "checkpoint_bytes": checkpoint.stat().st_size,
        "install_bytes": directory_bytes(install_root / ".venv"),
        "platform": f"{platform.system()} {platform.release()} {platform.machine()}",
        "startup_ms": startup_ms,
        "inference_ms": inference_ms,
        "rss_before_bytes": rss_before,
        "rss_loaded_bytes": rss_loaded,
        "rss_model_delta_bytes": max(0, rss_loaded - rss_before),
        "deterministic_tasks": deterministic_matches,
        "deterministic_task_total": len(TASKS),
        "repeat_hashes": repeat_hashes,
        "gate": notochord_gate(),
        "result": result,
        "validation": validation,
    }


def deterministic_screen() -> dict[str, Any]:
    cohort = make_cohort()
    rerun = make_cohort()
    deterministic = deterministic_results(cohort)
    validation = validate_result({**deterministic, "arm": "extracted-structure"}, "extracted-structure", cohort)
    invalid = deepcopy(deterministic["results"]["motif_variation"]["patch"])
    invalid["ops"][0]["notes"][0]["start"] = "8193/1024"
    _, timing_errors = compile_task_patch("motif_variation", invalid, cohort)
    stale = deepcopy(deterministic["results"]["motif_variation"]["patch"])
    stale["base_sha256"] = "stale"
    _, stale_errors = compile_task_patch("motif_variation", stale, cohort)
    collision = deepcopy(deterministic["results"]["motif_variation"]["patch"])
    collision["ops"][0]["notes"][1].update(collision["ops"][0]["notes"][0])
    collision["ops"][0]["notes"][1]["id"] = "motif_variation-collision"
    _, collision_errors = compile_task_patch("motif_variation", collision, cohort)
    return {
        "cohort_sha256": cohort["sha256"],
        "repeat_sha256": rerun["sha256"],
        "deterministic": cohort["sha256"] == rerun["sha256"],
        "pairs": len(cohort["pairs"]),
        "tasks": len(TASKS),
        "references": {key: {"sha256": value["sha256"], "permission": value["permission"], "coverage": value["coverage"]} for key, value in cohort["references"].items()},
        "baseline_valid_tasks": validation["valid_tasks"],
        "baseline_trait_score": [validation["trait_passed"], validation["trait_total"]],
        "refusals": {"unsupported_timing": timing_errors, "stale_source": stale_errors, "collision": collision_errors},
        "notochord": notochord_gate(),
    }


def max_rss_bytes() -> int:
    value = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return int(value if platform.system() == "Darwin" else value * 1024)


def run_provider(provider: str, env_file: Path) -> dict[str, Any]:
    environment = base.load_env(env_file)
    key_name = "OPENAI_API_KEY" if provider == "openai" else "GEMINI_API_KEY"
    if not environment.get(key_name):
        raise ValueError(f"{key_name} is missing")
    cohort = make_cohort()
    results = []
    for arm in ARMS:
        prompt = task_prompt(arm, cohort)
        before_rss = max_rss_bytes()
        started = time.perf_counter()
        value, raw = base.model_call(provider, environment[key_name], [{"role": "user", "content": prompt}], 14000)
        latency_ms = (time.perf_counter() - started) * 1000
        validation = validate_result(value, arm, cohort)
        initial_value = value
        initial_validation = validation
        correction = None
        if validation["valid_tasks"] < len(TASKS):
            started = time.perf_counter()
            repaired, repair_raw = base.model_call(provider, environment[key_name], [
                {"role": "user", "content": prompt}, {"role": "assistant", "content": canonical(value)}, {"role": "user", "content": repair_prompt(validation)},
            ], 14000)
            correction = {
                "turns": 1,
                "latency_ms": (time.perf_counter() - started) * 1000,
                "usage": base.usage(provider, repair_raw),
                "returned_model": base.returned_model(provider, repair_raw),
                "request_id": repair_raw.get("id"),
                "result": repaired,
                "validation": validate_result(repaired, arm, cohort),
            }
            value = repaired
            validation = correction["validation"]
        results.append({
            "arm": arm,
            "prompt_sha256": hashlib.sha256(prompt.encode()).hexdigest(),
            "prompt_utf8_bytes": len(prompt.encode()),
            "reference_coverage": coverage_for_arm(arm, cohort),
            "initial": {
                "latency_ms": latency_ms, "usage": base.usage(provider, raw),
                "returned_model": base.returned_model(provider, raw), "request_id": raw.get("id"),
                "result": initial_value,
                "validation": initial_validation,
            },
            "correction": correction,
            "peak_rss_delta_bytes": max(0, max_rss_bytes() - before_rss),
            "result": value,
            "validation": validation,
        })
    return {
        "schema": SCHEMA,
        "provider": provider,
        "requested_model": base.OPENAI_MODEL if provider == "openai" else base.GEMINI_MODEL,
        "client": "Python urllib.request direct HTTPS",
        "model_settings": {"reasoning_or_thinking": "low", "temperature": None if provider == "openai" else 0},
        "platform": f"{platform.system()} {platform.release()} {platform.machine()}",
        "privacy": "Generated MIT project fixtures only. No third-party notes or live project data.",
        "cohort_sha256": cohort["sha256"],
        "screen": deterministic_screen(),
        "results": results,
    }


def summarize(paths: list[Path]) -> dict[str, Any]:
    runs = [json.loads(path.read_text()) for path in paths]
    rows = []
    for run in runs:
        for item in run["results"]:
            validation = item["validation"]
            copy_counts = [source["exact_event_count"] for task in validation["tasks"].values() for source in task["direct_copy"].values()]
            rows.append({
                "provider": run["provider"], "model": item["initial"]["returned_model"], "arm": item["arm"],
                "valid_tasks": validation["valid_tasks"], "task_total": len(TASKS), "trait_passed": validation["trait_passed"], "trait_total": validation["trait_total"],
                "exact_event_copies": sum(copy_counts), "correction_turns": 0 if item["correction"] is None else 1,
                "input_tokens": item["initial"]["usage"]["input_tokens"], "output_tokens": item["initial"]["usage"]["output_tokens"],
                "latency_ms": item["initial"]["latency_ms"], "peak_rss_delta_bytes": item["peak_rss_delta_bytes"],
            })
    return {"schema": SCHEMA, "source_sha256": {str(path): hashlib.sha256(path.read_bytes()).hexdigest() for path in paths}, "rows": rows, "notochord": notochord_gate()}


def ballot(paths: list[Path], output: Path, key_output: Path, seed: str) -> dict[str, Any]:
    runs = [json.loads(path.read_text()) for path in paths]
    cohort = make_cohort()
    candidates: dict[str, list[dict[str, Any]]] = {task: [] for task in TASKS}
    for run in runs:
        for item in run["results"]:
            for task, validation in item["validation"]["tasks"].items():
                if validation["valid"]:
                    candidates[task].append({"source": f"{run['provider']}:{item['arm']}", "notes": validation["compiled_notes"]})
    baseline = deterministic_results(cohort)
    baseline_validation = validate_result({**baseline, "arm": "extracted-structure"}, "extracted-structure", cohort)
    for task, validation in baseline_validation["tasks"].items():
        candidates[task].append({"source": "deterministic", "notes": validation["compiled_notes"]})
    rng = random.Random(seed)
    audio_dir = output.parent / f"{output.stem}-audio"
    audio_dir.mkdir(parents=True, exist_ok=True)
    key = {"schema": "ghostnote-reference-ballot-key-v0", "seed": seed, "tasks": {}}
    lines = ["# Phase 6g blind operator ballot", "", "Review each task without trying to identify the source. Rank the candidates from best to worst. Use `cannot-decide` when needed.", ""]
    for task in TASKS:
        rng.shuffle(candidates[task])
        pair = next(row for row in cohort["pairs"].values() if task in row["tasks"])
        seed_clip = cohort["seeds"][pair["seed_id"]]
        seed_path = audio_dir / f"{task}-seed.wav"
        render_audio(seed_clip["notes"], Fraction(), seed_path)
        lines.extend((
            f"## {task}", "", TASK_LIMITS[task]["required"], "",
            f"Shared seed only: [{seed_path.name}](<{seed_path}>)", "",
            "Each candidate audio plays this same seed, then its generated region.", "",
        ))
        for reference_id in pair["reference_ids"]:
            reference = cohort["references"][reference_id]
            reference_path = audio_dir / f"{task}-{reference_id}.wav"
            render_audio(reference["notes"], Fraction(), reference_path)
            lines.extend((f"Shared reference {reference_id}: [{reference_path.name}](<{reference_path}>)", ""))
        key["tasks"][task] = {}
        for index, candidate in enumerate(candidates[task]):
            alias = chr(ord("A") + index)
            key["tasks"][task][alias] = candidate["source"]
            audio_path = audio_dir / f"{task}-{alias}.wav"
            render_audio(seed_clip["notes"] + candidate["notes"], Fraction(), audio_path)
            lines.append(f"### Candidate {alias}")
            lines.append("")
            lines.append(f"Audio: [{audio_path.name}](<{audio_path}>)")
            lines.append("")
            lines.append("```text")
            for row in sorted(candidate["notes"], key=lambda value: (frac(value["start"]), value["track"], value["pitch"])):
                lines.append(f"{row['track']} at={row['start']} dur={row['duration']} pitch={row['pitch']} velocity={row['velocity']}")
            lines.extend(("```", ""))
        lines.extend(("Ranking:", "", "Notes:", ""))
    output.write_text("\n".join(lines))
    key_output.write_text(json.dumps(key, indent=2, sort_keys=True) + "\n")
    return {"ballot": str(output), "key": str(key_output), "audio_dir": str(audio_dir), "tasks": len(TASKS), "candidates_per_task": {task: len(rows) for task, rows in candidates.items()}, "seed": seed}


def render_audio(notes: list[dict[str, Any]], origin: Fraction, path: Path, sample_rate: int = 22050) -> None:
    duration_beats = max((frac(row["start"]) + frac(row["duration"]) - origin for row in notes), default=Fraction(1))
    sample_count = max(1, int((float(duration_beats) * 0.5 + 0.25) * sample_rate))
    samples = [0.0] * sample_count
    for row in notes:
        start = max(0, int(float(frac(row["start"]) - origin) * 0.5 * sample_rate))
        end = min(sample_count, start + max(1, int(float(frac(row["duration"])) * 0.5 * sample_rate)))
        amplitude = 0.08 * row["velocity"] / 127
        if "drums" in row["track"]:
            noise = random.Random(int(hashlib.sha256(row["id"].encode()).hexdigest()[:8], 16))
            for index in range(start, min(end, start + sample_rate // 8)):
                envelope = 1 - (index - start) / max(1, sample_rate // 8)
                samples[index] += amplitude * envelope * (noise.random() * 2 - 1)
            continue
        frequency = 440 * 2 ** ((row["pitch"] - 69) / 12)
        attack = max(1, sample_rate // 100)
        release = max(1, sample_rate // 50)
        for index in range(start, end):
            offset = index - start
            remaining = end - index
            envelope = min(1.0, offset / attack, remaining / release)
            phase = 2 * math.pi * frequency * offset / sample_rate
            tone = math.sin(phase)
            if "lead" in row["track"]:
                tone += 0.25 * math.sin(phase * 2)
            elif "chords" in row["track"] or "keys" in row["track"]:
                tone += 0.18 * math.sin(phase * 3)
            samples[index] += amplitude * envelope * tone
    peak = max((abs(value) for value in samples), default=1)
    scale = 0.9 / max(0.9, peak)
    with wave.open(str(path), "wb") as output_file:
        output_file.setnchannels(1)
        output_file.setsampwidth(2)
        output_file.setframerate(sample_rate)
        output_file.writeframes(b"".join(struct.pack("<h", round(max(-1, min(1, value * scale)) * 32767)) for value in samples))


def self_test() -> dict[str, Any]:
    cohort = make_cohort()
    assert len(cohort["pairs"]) == 3 and len(TASKS) == 6
    assert len(cohort["references"]) == 4
    assert make_cohort()["sha256"] == cohort["sha256"]
    assert all(item["permission"] == PERMISSION for item in cohort["references"].values())
    assert "No reference content" in render_context("seed-only", cohort)
    assert "p65" in render_context("raw-reference", cohort)
    assert "pitch_interval_signs" in render_context("extracted-structure", cohort)
    assert "SELECTED EXCERPT" in render_context("mixed", cohort)
    deterministic = deterministic_results(cohort)
    validation = validate_result({**deterministic, "arm": "extracted-structure"}, "extracted-structure", cohort)
    assert validation["valid_tasks"] == 6
    assert validation["trait_passed"] == validation["trait_total"]
    screen = deterministic_screen()
    assert screen["deterministic"] and screen["baseline_valid_tasks"] == 6
    assert screen["refusals"]["unsupported_timing"]
    assert screen["refusals"]["stale_source"]
    assert screen["refusals"]["collision"]
    assert notochord_gate()["classification"] == "approved-for-bounded-experiment"
    return {"passed": 14, "cohort_sha256": cohort["sha256"], "screen": screen}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--provider", choices=PROVIDERS)
    parser.add_argument("--notochord", action="store_true")
    parser.add_argument("--checkpoint", type=Path)
    parser.add_argument("--install-root", type=Path)
    parser.add_argument("--env-file", type=Path, default=Path(".env"))
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--summarize", nargs="*", type=Path)
    parser.add_argument("--ballot", nargs="*", type=Path)
    parser.add_argument("--ballot-key", type=Path)
    parser.add_argument("--ballot-seed", default="phase6g-blind-v0")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if args.self_test:
        result = self_test()
    elif args.notochord:
        if args.checkpoint is None or args.install_root is None:
            parser.error("--notochord needs --checkpoint and --install-root")
        result = run_notochord(args.checkpoint, args.install_root)
    elif args.summarize:
        result = summarize(args.summarize)
    elif args.ballot:
        if args.output is None or args.ballot_key is None:
            parser.error("--ballot needs --output and --ballot-key")
        result = ballot(args.ballot, args.output, args.ballot_key, args.ballot_seed)
        print(json.dumps(result, indent=2, sort_keys=True))
        return
    elif args.provider:
        result = run_provider(args.provider, args.env_file)
    else:
        parser.error("select --self-test, --notochord, --provider, --summarize, or --ballot")
    rendered = json.dumps(result, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.write_text(rendered)
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
